class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startadult'
        self.MirrorCommand = 'mirroradult'
        self.UnzipMirrorCommand = 'unzipmirroradult'
        self.TarMirrorCommand = 'tarmirroradult'
        self.CancelMirror = 'canceladult'
        self.CancelAllCommand = 'cancelalladult'
        self.ListCommand = 'listadult'
        self.StatusCommand = 'statusadult'
        self.AuthorizedUsersCommand = 'usersadult'
        self.AuthorizeCommand = 'authorizeadult'
        self.UnAuthorizeCommand = 'unauthorizeadult'
        self.AddSudoCommand = 'addsudoadult'
        self.RmSudoCommand = 'rmsudoadult'
        self.PingCommand = 'pingadult'
        self.RestartCommand = 'restartadult'
        self.StatsCommand = 'statsadult'
        self.HelpCommand = 'helpadult'
        self.LogCommand = 'logadult'
        self.SpeedCommand = 'speedtestadult'
        self.CloneCommand = 'cloneadult'
        self.CountCommand = 'countadult'
        self.WatchCommand = 'watchadult'
        self.TarWatchCommand = 'tarwatchadult'
        self.DeleteCommand = 'deladult'
        self.UsageCommand = 'usageadult'
        self.MediaInfoCommand = 'mediainfoadult'
        self.ConfigMenuCommand = 'configadult'
        self.ShellCommand = 'shelladult'
        self.UpdateCommand = 'updateadult'

BotCommands = _BotCommands()
